"""empty message

Revision ID: 00e980216f84
Revises: ca68ec284271
Create Date: 2024-11-18 05:56:19.929597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e980216f84'
down_revision = 'ca68ec284271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.PickleType(), nullable=True))
        batch_op.drop_column('times_to_take_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_to_take_at', sa.BLOB(), nullable=True))
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###
