"""empty message

Revision ID: b44b748ae807
Revises: b7dd97db664f
Create Date: 2024-11-18 07:27:47.049465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44b748ae807'
down_revision = 'b7dd97db664f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
