"""empty message

Revision ID: b7dd97db664f
Revises: 00e980216f84
Create Date: 2024-11-18 06:56:43.400281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dd97db664f'
down_revision = '00e980216f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reminder_number', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('time_to_take_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('on_off', sa.BOOLEAN(), nullable=False),
    sa.Column('changed_time', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['time_to_take_id'], ['time_to_take.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
