"""Initial migration

Revision ID: ca68ec284271
Revises: 
Create Date: 2024-11-18 03:39:44.138357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca68ec284271'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosage', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('times_per_day', sa.Integer(), nullable=True))
        batch_op.drop_column('times_to_take')
        batch_op.drop_column('dose')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dose', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('times_to_take', sa.INTEGER(), nullable=False))
        batch_op.drop_column('times_per_day')
        batch_op.drop_column('end_date')
        batch_op.drop_column('dosage')

    # ### end Alembic commands ###
